---
# tasks file for webmin on Ubuntu
- name: apt-get install dependencies
  ansible.builtin.apt:
    name: "{{ item.name }}"
    state: "{{ item.state }}"
  with_items:
    - { state: "latest", name: "perl" }
    - { state: "latest", name: "libnet-ssleay-perl" }
    - { state: "latest", name: "openssl" }
    - { state: "latest", name: "libauthen-pam-perl" }
    - { state: "latest", name: "libpam-runtime" }
    - { state: "latest", name: "libio-pty-perl" }
    - { state: "latest", name: "apt-show-versions" }
  tags: [ dependencies ]

- name: apt-key add
  ansible.builtin.apt_key:
    url: "{{ item.url }}"
    state: "{{ item.state }}"
  with_items:
    - { state: "present", url: "http://www.webmin.com/jcameron-key.asc" }
  notify: restart webmin
  tags: [ webmin ]

- name: apt-add-repository
  ansible.builtin.apt_repository:
    repo: "{{ item.repo }}"
    state: "{{ item.state }}"
  with_items:
    - { state: "present", repo: "deb http://download.webmin.com/download/repository sarge contrib" }
  notify: restart webmin
  tags: [ webmin ]

- name: apt-get install
  ansible.builtin.apt:
    name: "{{ item.name }}"
    state: "{{ item.state }}"
  with_items:
    - { state: "latest", name: "webmin" }
  notify: restart webmin
  tags: [ webmin ]

- name: replace in file
  ansible.builtin.replace:
    dest: "{{ item.dest }}"
    regexp: "{{ item.regexp }}"
    replace: "{{ item.replace }}"
  with_items:
    - { dest: "/etc/webmin/miniserv.conf", regexp: "^listen=.*$", replace: "listen={{ webmin_listen }}" }
    - { dest: "/etc/webmin/miniserv.conf", regexp: "^port=.*$", replace: "port={{ webmin_port }}" }
    - { dest: "/etc/webmin/miniserv.conf", regexp: "^ssl=.*$", replace: "ssl={{ webmin_ssl }}" }
  notify: restart webmin
  tags: [ webmin ]

- name: set reverse proxy referer
  ansible.builtin.replace:
    dest: "{{ item.dest }}"
    regexp: "{{ item.regexp }}"
    replace: "{{ item.replace }}"
  with_items:
    - { dest: "/etc/webmin/miniserv.conf", regexp: "^referers=.*$", replace: "referers={{ webmin_reverse_proxy_referer }}" }
  when: webmin_reverse_proxy_referer is defined and webmin_reverse_proxy_referer|length>10
  notify: restart webmin
  tags: [ webmin ]  

- name: Wait 10 seconds for port {{ webmin_port }} to start up
  ansible.builtin.wait_for:
    port: "{{ webmin_port }}"
    delay: 10    
